### ISSUE TITLE
Kanban Board Done

### ISSUE THREAD

**Issue by Juanse7793** [Juanse7793/Catalog-in-Ruby#38]
[Link](https://github.com/Juanse7793/Catalog-in-Ruby/projects/1) to the project 

I'm alone in this project

Student A,B and C is me @Juanse7793

**Comment by VICTOR-CHUKWU** [comment]
Hi @Juanse7793 ,
# STATUS: APPROVED! 🥇 💯 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
